import { defineElement } from "@neo-builder/core";
import { tokens, style, sanitizeInlineHtml } from "./util.js";

/** A run of rich text: paragraph or heading. `content` is inline HTML. */
export const text = defineElement({
  type: "text",
  label: "Text",
  icon: "T",
  category: "Content",
  version: 1,
  schema: {
    props: {
      content: "inline rich-text HTML (bold/italic/links)",
      as: "'p' | 'h1' | 'h2' | 'h3'",
      align: "'left' | 'center' | 'right'",
      size: "optional type-scale override: 'xs'|'sm'|'base'|'lg'|'xl'|'2xl'|'3xl'|'4xl'",
      weight: "optional: 'normal'|'medium'|'bold'|'heavy'",
      color: "optional: color token 'text'|'muted'|'primary' or a literal CSS color like '#ffffff'",
      maxWidth: "optional CSS max-width, e.g. '38rem' — keeps line length readable",
    },
  },
  aiMeta: {
    description: "A block of rich text — paragraph or heading. The main content Element.",
    props: {
      content:
        "Inline HTML with a small formatting allowlist (b/strong, i/em, u, s, a, br, span). The thing most often regenerated by the AI loop. Avoid block tags.",
      as: "Semantic level; headings use the heading font, tight leading and larger sizes.",
      align: "Horizontal alignment.",
      size: "Overrides the size implied by `as`. Use '3xl'/'4xl' for display headlines.",
      weight: "Overrides the weight implied by `as` (headings default bold/heavy).",
      color: "'muted' for secondary copy, 'primary' for accented lines.",
      maxWidth: "Set on hero subheads/paragraphs so lines don't run wall-to-wall.",
    },
  },
  defaults: () => ({ content: "Text", as: "p", align: "left" }),
  render: {
    html: (node, ctx) => {
      const t = tokens(ctx);
      const as = String(node.props.as ?? "p");
      const tag = ["p", "h1", "h2", "h3"].includes(as) ? as : "p";
      const isHeading = tag !== "p";
      const sizeMap: Record<string, number> = {
        h1: t.fontSizes["2xl"],
        h2: t.fontSizes.xl,
        h3: t.fontSizes.lg,
        p: t.fontSizes.base,
      };
      const sizeKey = String(node.props.size ?? "");
      const size =
        (t.fontSizes as Record<string, number>)[sizeKey] ?? sizeMap[tag] ?? t.fontSizes.base;
      const weightMap: Record<string, number> = {
        h1: t.fontWeights.heavy,
        h2: t.fontWeights.bold,
        h3: t.fontWeights.bold,
        p: t.fontWeights.normal,
      };
      const weightKey = String(node.props.weight ?? "");
      const weight =
        (t.fontWeights as Record<string, number>)[weightKey] ?? weightMap[tag] ?? t.fontWeights.normal;
      const colorKey = String(node.props.color ?? "text");
      // Token name, or a literal CSS color ("#fff", "rgba(…)") — agents use both.
      const color = /^(#|rgb|hsl)/i.test(colorKey)
        ? colorKey
        : ((t.colors as Record<string, string>)[colorKey] ?? t.colors.text);
      const align = String(node.props.align ?? "left");
      const maxWidth = node.props.maxWidth ? String(node.props.maxWidth) : "";
      const s = style({
        margin: maxWidth && align === "center" ? "0 auto" : "0",
        "font-family": isHeading ? t.fonts.heading : t.fonts.body,
        "font-size": `${size}px`,
        "font-weight": String(weight),
        "line-height": String(isHeading ? t.lineHeights.tight : t.lineHeights.normal),
        "letter-spacing": isHeading ? `${t.letterSpacing.tight}em` : undefined,
        color,
        "text-align": align,
        "max-width": maxWidth || undefined,
      });
      return `<${tag}${s}>${sanitizeInlineHtml(node.props.content)}</${tag}>`;
    },
    mjml: (node, ctx) => {
      const t = tokens(ctx);
      const as = String(node.props.as ?? "p");
      const isHeading = as !== "p";
      const sizeMap: Record<string, number> = {
        h1: t.fontSizes["2xl"],
        h2: t.fontSizes.xl,
        h3: t.fontSizes.lg,
        p: t.fontSizes.base,
      };
      const sizeKey = String(node.props.size ?? "");
      const size =
        (t.fontSizes as Record<string, number>)[sizeKey] ?? sizeMap[as] ?? t.fontSizes.base;
      const colorKey = String(node.props.color ?? "text");
      const color = /^(#|rgb|hsl)/i.test(colorKey)
        ? colorKey
        : ((t.colors as Record<string, string>)[colorKey] ?? t.colors.text);
      const weight = isHeading ? t.fontWeights.bold : t.fontWeights.normal;
      return (
        `<mj-text font-family="${isHeading ? t.fonts.heading : t.fonts.body}" ` +
        `font-size="${size}px" font-weight="${weight}" color="${color}" ` +
        `line-height="${isHeading ? t.lineHeights.tight : t.lineHeights.normal}" ` +
        `align="${String(node.props.align ?? "left")}">` +
        `${sanitizeInlineHtml(node.props.content)}</mj-text>`
      );
    },
    form: (node) => JSON.stringify({ kind: "static", text: node.props.content, as: node.props.as }),
  },
});
